# Generated by Django 2.2.6 on 2019-10-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('_id', models.CharField(max_length=500, primary_key=True, serialize=False, unique=True)),
                ('photoName', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=1000, serialize=False, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
