# Generated by Django 2.2.6 on 2019-10-15 03:03

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=500, unique=True)),
                ('photoName', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('tags', djongo.models.fields.ArrayModelField(model_container='Tag')),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User')),
            ],
        ),
    ]
