# Generated by Django 2.2.6 on 2019-10-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photorepo', '0002_auto_20191016_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
